# Generated by Django 6.0.3 on 2026-04-18 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maidapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
