# Generated by Django 6.0.3 on 2026-04-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maidapp', '0002_customuser_session_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=100)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.IntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='workerprofile',
            name='aadhar_photo',
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='aadhar_back',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/aadhar/'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='aadhar_front',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/aadhar/'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='kyc_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='selfie',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/selfies/'),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='pan_photo',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/pan/'),
        ),
    ]
