# Generated by Django 6.0.3 on 2026-04-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maidapp', '0002_category_booking_end_time_booking_service_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_doc_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_otp_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='aadhar_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='aadhar_photo',
            field=models.ImageField(blank=True, null=True, upload_to='docs/'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='pan_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='pan_photo',
            field=models.ImageField(blank=True, null=True, upload_to='docs/'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
