# Generated by Django 6.0.4 on 2026-04-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maidapp', '0003_otpverification_remove_workerprofile_aadhar_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='service_type',
            field=models.CharField(default='general', help_text='Specific service chosen', max_length=100),
            preserve_default=False,
        ),
    ]
