# Generated by Django 6.0.3 on 2026-04-16 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maidapp', '0003_customuser_is_doc_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_id_str',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
