# Generated by Django 6.0.3 on 2026-04-20 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maidapp', '0004_booking_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='delivery_method',
            field=models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], default='email', max_length=10),
        ),
    ]
