# Generated by Django 6.0.3 on 2026-04-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maidapp', '0007_customuser_is_blocked_workerprofile_kyc_submitted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='kyc_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
