# Generated by Django 6.0.3 on 2026-04-28 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maidapp', '0012_category_slug_alter_booking_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('busy', 'Busy')], default='available', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('paid', 'Paid'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
