# Generated by Django 6.0.3 on 2026-04-28 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maidapp', '0013_workerprofile_status_alter_booking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('discount_percent', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('offer_type', models.CharField(choices=[('first_time', 'First Time'), ('weekend', 'Weekend'), ('general', 'General')], default='general', max_length=20)),
            ],
        ),
    ]
