# Generated by Django 6.0.3 on 2026-04-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maidapp', '0014_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='code',
            field=models.CharField(blank=True, help_text='e.g. WELCOME20', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='max_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='min_order_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='usage_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of times this offer can be used', null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='used_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
