# Generated by Django 6.0.3 on 2026-04-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maidapp', '0015_offer_code_offer_max_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
