# Generated by Django 6.0.3 on 2026-04-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maidapp', '0016_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='is_online',
            field=models.BooleanField(default=True),
        ),
    ]
