# Generated by Django 6.0.3 on 2026-04-29 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maidapp', '0018_userprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_offer_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
