# Generated by Django 6.0.3 on 2026-04-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maidapp', '0019_customuser_last_offer_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='offer_applied',
            field=models.BooleanField(default=False),
        ),
    ]
