# Generated by Django 6.0.3 on 2026-04-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maidapp', '0020_booking_offer_applied'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartOfferSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('inactive_days_threshold', models.PositiveIntegerField(default=30, help_text="Days since last booking to consider user 'Inactive'")),
                ('default_duration_minutes', models.PositiveIntegerField(default=10)),
            ],
            options={
                'verbose_name_plural': 'Smart Offer Settings',
            },
        ),
        migrations.AddField(
            model_name='offer',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=10, help_text='How many minutes the offer remains valid after being unlocked'),
        ),
        migrations.AddField(
            model_name='offer',
            name='target_user_type',
            field=models.CharField(choices=[('new', 'New User (No Bookings)'), ('regular', 'Regular User'), ('inactive', 'Inactive User (X days since last booking)'), ('general', 'All Users')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('first_time', 'First Time'), ('weekend', 'Weekend'), ('general', 'General'), ('smart', 'Smart Offer (Automatic Popup)')], default='general', max_length=20),
        ),
    ]
