# Generated by Django 6.0.3 on 2026-04-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maidapp', '0021_smartoffersettings_offer_duration_minutes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='discount_percent',
            new_name='discount',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='used_count',
            new_name='usage_count',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='target_user_type',
            new_name='user_type',
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('smart', 'Smart Offer (Automatic Popup)'), ('general', 'General'), ('first_time', 'First Time'), ('weekend', 'Weekend')], default='general', max_length=20),
        ),
    ]
