# Generated by Django 6.0.3 on 2026-04-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maidapp', '0022_rename_discount_percent_offer_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='daily_target',
            field=models.IntegerField(default=500, help_text='Dynamic daily earning goal for the worker'),
        ),
    ]
